#!/bin/bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac or Linux system and be up
# and running very quickly.
tmux source .tmux.conf
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
# ln -sf "$PWD/skhdrc" "$XDG_CONFIG_HOME"/skhd/skhdrc
# ln -sf "$PWD/newsboat/config" "$HOME"/.newsboat/config
# ln -sf "$PWD/newsboat/urls" "$HOME"/.newsboat/urls

# Packages

# install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install --cask alacritty

# brew packages Mac
# amethyst fzf nvim exa hugo bash-completion@2 newsboat kubectl starship

# ubuntu packages apt
brew install ripgrep gh starship

# ubuntu apt neovim setup
brew install gcc g++ unzip

# ubuntu brew for vim and neovim setup
# sudo apt install fd fzf kubectl kubectx derailed/k9s/k9s
brew install fd fzf

# ubuntu brew for neovim setup
brew install neovim go lazygit

# ubuntu specific notes
# create symbolic link to neovim from vim when not using neovim on
# Ubuntu systems, because I use the v alias everywhere.
# sudo ln -sf /usr/bin/vim /usr/bin/nvim
