#!/bin/bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac or Linux system and be up
# and running very quickly.
tmux source .tmux.conf
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
# ln -sf "$PWD/skhdrc" "$XDG_CONFIG_HOME"/skhd/skhdrc
# ln -sf "$PWD/newsboat/config" "$HOME"/.newsboat/config
# ln -sf "$PWD/newsboat/urls" "$HOME"/.newsboat/urls

# Packages

# install brew if not present
if ! command -v brew &>/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# install everything from Brewfile
brew bundle --file="$PWD/Brewfile"
